# Generated by Django 5.2.6 on 2026-10-06 16:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True, verbose_name='matricula')),
                ('nome', models.CharField(max_length=120, verbose_name='nome')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'aluno',
                'verbose_name_plural': 'alunos',
                'db_table': 'aluno',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='codigo')),
                ('nome', models.CharField(max_length=120, verbose_name='nome')),
                ('carga_horaria', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='carga horaria')),
                ('periodo', models.IntegerField(blank=True, null=True, verbose_name='periodo')),
            ],
            options={
                'verbose_name': 'disciplina',
                'verbose_name_plural': 'disciplinas',
                'db_table': 'disciplina',
                'ordering': ['periodo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota1', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='1a nota')),
                ('nota2', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='2a nota')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscricoes', to='academico.aluno', verbose_name='aluno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscricoes', to='academico.disciplina', verbose_name='disciplina')),
            ],
            options={
                'verbose_name': 'inscricao',
                'verbose_name_plural': 'inscricoes',
                'db_table': 'inscricao',
                'ordering': ['aluno', 'disciplina'],
                'constraints': [models.UniqueConstraint(fields=('aluno', 'disciplina'), name='inscricao_unica_por_aluno_disciplina')],
            },
        ),
    ]
